sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cbienaime/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cbienaime/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker"
    env: "Docker-env-1"
    bucket_name: "elasticbeanstalk-eu-west-3-832494246431"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY