sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cbienaime/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cbienaime/docker-react npm run test